---
title: "Analysis Workflow"
author: "Yuriy Sverchkov"
date: "9/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data loading and preprocessing

### Load data
```{r eval = F}
source( "R/load-data.R" )
```

### Make molecule ID table
```{r eval = F}
source( "R/make-master-molecule-id-table.R")
```

### Make long table
```{r eval = F}
source( "R/make-long-table.R")
```

### Run t-tests
```{r eval = F}
source( "R/t-test-long-table.R")
```

### Making feature matrix
```{r eval = F}
library( dplyr )
library( tidyr )

feature_df <- tested_table %>%
  select( `Molecule ID`, Knockout, `t statistic` ) %>%
  spread( key = Knockout, value = `t statistic` )

saveRDS( feature_df, "processed-data/feature_t_df.rds" )
```

```{r echo=FALSE, results='asis'}
if ( any( is.na( feature_df ) ) )
  cat("**Note:** `feature_df` contains `NA` values.")
```

## Analysis

### Correlational network analysis

#### Obtain correlation matrix
```{r eval = F}
source( "R/compute-cosine-smimilarity.R" ) # Takes a while, best to run in separate process. Condor version also exists.
```

### Factor Graph Nested Effects Model

### Backgroun network mapping

